### ISSUE TITLE
Create only Object

### ISSUE THREAD

**Issue by marckaraujo** [clarkie/dynogels#25]
How I know that this object was not created before?

When I run this code with the same values, it never got error.
The hashkey is username.
It dont create another item in Dynamodb but I doesnt know if it was previously created or if it is a new record.

```
User.create({username: event.username, password: event.password}, {overwrite : false}, function (err, acc) {
    if (err == null) {
        console.log('created account in DynamoDB', acc);
        var response = {
            status: "true",
            data: {
                username: event.username,
                password: event.password
            },
            error: []
        };
        return cb(null, response);
    } else {
        console.log(err);
        var response = {
            status: "false",
            data: {
                username: event.username,
                password: event.password
            },
            error: []
        };
        return cb(null, response);
    }
});
```

**Comment by clarkie** [comment]
This is a limitation of the underlying database. A couple of points that may be useful:

1. You can't have more than one record with the same hash key (when not using a range key)
2. When creating an item in dynamodb the process is idempotent (similar to a PUT http request)
3. If you create an item with a duplicate hash key it will by default overwrite the original record

To get around this the dynamodb docs offer the following advice:

> To prevent a new item from replacing an existing item, use a conditional expression that contains the attribute_not_exists function with the name of the attribute being used as the partition key for the table. Since every record must contain that attribute, the attribute_not_exists function will only succeed if no matching item exists.

In Dynogels this is exposed as `{overwrite: false}` so you don't need to worry about constructing the conditional expression. 

If I have misunderstood your question can you post your schema so that I can dig a bit further.

This [question](http://stackoverflow.com/questions/12457130/what-will-happen-if-we-insert-into-dynamo-db-with-a-duplicate-hash-key) asks a very similar question.
